import { useEffect, useRef, useState } from "react";
import { Card } from "../components/Common/Card";
import { TextArea } from "../components/Common/TextArea";
import { Button } from "../components/Common/Button";
import { Spinner } from "../components/Common/Spinner";
import { SkeletonLoader } from "../components/Common/SkeletonLoader";
import { EmptyState } from "../components/Common/EmptyState";
import { ErrorState } from "../components/Common/ErrorState";
import { RecentHistory } from "../components/Common/RecentHistory";
import { FlashcardDeck } from "../components/Flashcards/FlashcardDeck";
import { QuizContainer } from "../components/Quiz/QuizContainer";
import { useGenerate } from "../hooks/useGenerate";
import { useHistory } from "../hooks/useHistory";
import { MIN_INPUT_CHARS, MODES } from "../constants";

export function Home() {
  const [inputText, setInputText] = useState("");
  const [mode, setMode] = useState(null);
  const [copyLabel, setCopyLabel] = useState("Copy notes");
  const isRestoringRef = useRef(false);

  const { status, data, error, generate, loadCached, isLoading } = useGenerate();
  const { history, addEntry, removeEntry, clearHistory } = useHistory();

  const isInputValid = inputText.trim().length >= MIN_INPUT_CHARS;

  useEffect(() => {
    if (status === "success" && data && mode && !isRestoringRef.current) {
      addEntry({ mode, title: data.title, inputText, data });
    }
    isRestoringRef.current = false;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status, data]);

  function handleGenerate(nextMode) {
    if (!isInputValid || isLoading) return;
    setMode(nextMode);
    generate(inputText, nextMode);
  }

  function handleRetry() {
    if (mode) generate(inputText, mode);
  }

  function handleSelectHistory(entry) {
    isRestoringRef.current = true;
    setInputText(entry.inputText);
    setMode(entry.mode);
    loadCached(entry.data);
  }

  async function handleCopy() {
    if (!inputText) return;
    try {
      await navigator.clipboard.writeText(inputText);
      setCopyLabel("Copied!");
      setTimeout(() => setCopyLabel("Copy notes"), 1500);
    } catch {
      setCopyLabel("Copy failed");
      setTimeout(() => setCopyLabel("Copy notes"), 1500);
    }
  }

  return (
    <div className="space-y-10">
      <div className="text-center">
        <h1 className="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl dark:text-white">
          Turn notes into study tools, instantly
        </h1>
        <p className="mx-auto mt-3 max-w-xl text-gray-500 dark:text-gray-400">
          Paste your notes or type any topic — get interactive flashcards or a quiz generated by AI.
        </p>
      </div>

      <Card className="p-5 sm:p-6">
        <TextArea
          value={inputText}
          onChange={setInputText}
          placeholder="Paste your study notes or enter any topic..."
          disabled={isLoading}
        />

        <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
          <Button variant="ghost" size="sm" onClick={handleCopy} disabled={!inputText}>
            {copyLabel}
          </Button>

          <div className="flex flex-wrap gap-3">
            <Button
              variant="secondary"
              onClick={() => handleGenerate(MODES.FLASHCARDS)}
              disabled={!isInputValid || isLoading}
              icon={isLoading && mode === MODES.FLASHCARDS ? <Spinner size={16} /> : null}
            >
              {isLoading && mode === MODES.FLASHCARDS ? "Generating..." : "Generate Flashcards"}
            </Button>
            <Button
              variant="primary"
              onClick={() => handleGenerate(MODES.QUIZ)}
              disabled={!isInputValid || isLoading}
              icon={isLoading && mode === MODES.QUIZ ? <Spinner size={16} /> : null}
            >
              {isLoading && mode === MODES.QUIZ ? "Generating..." : "Generate Quiz"}
            </Button>
          </div>
        </div>
      </Card>

      <div>
        {status === "loading" && <SkeletonLoader variant={mode} />}

        {status === "error" && <ErrorState message={error} onRetry={handleRetry} />}

        {status === "success" && data?.type === "flashcards" && <FlashcardDeck deck={data} />}
        {status === "success" && data?.type === "quiz" && <QuizContainer quiz={data} />}

        {status === "idle" && (
          <>
            <EmptyState />
            <RecentHistory
              history={history}
              onSelect={handleSelectHistory}
              onRemove={removeEntry}
              onClear={clearHistory}
            />
          </>
        )}
      </div>
    </div>
  );
}
